const ActionType = {
  OPEN_LOGIN: 'OPEN_LOGIN',
  SUCCEED_LOGIN: 'SUCCEED_LOGIN',
  FAIL_LOGIN: 'FAIL_LOGIN',

  OPEN_SIGNUP: 'OPEN_SIGNUP',
  SUCCEED_SIGNUP: 'SUCCEED_SIGNUP',
  FAIL_SIGNUP: 'FAIL_SIGNUP',

  OPEN_CONFIRM_SIGNUP: 'OPEN_CONFIRM_SIGNUP',
  SUCCEED_CONFIRM_SIGNUP: 'SUCCEED_CONFIRM_SIGNUP',
  FAIL_CONFIRM_SIGNUP: 'FAIL_CONFIRM_SIGNUP',

  OPEN_PASSWORD_RESET: 'OPEN_PASSWORD_RESET',
  SUCCEED_PASSWORD_RESET: 'SUCCEED_PASSWORD_RESET',
  FAIL_PASSWORD_RESET: 'FAIL_PASSWORD_RESET',

  OPEN_CONFIRM_PASSWORD_RESET: 'OPEN_CONFIRM_PASSWORD_RESET',
  SUCCEED_CONFIRM_PASSWORD_RESET: 'SUCCEED_CONFIRM_PASSWORD_RESET',
  FAIL_CONFIRM_PASSWORD_RESET: 'FAIL_CONFIRM_PASSWORD_RESET',

  CLOSE_SIGNIN: 'CLOSE_SIGNIN',

  FAIL_CURRENT_USER: 'FAILED_CURRENT_USER',
  SUCCEED_CURRENT_USER: 'SUCCESS_CURRENT_USER',

  FAIL_LOGOUT: 'FAIL_LOGOUT'
};

export default ActionType;