INSERT INTO "Tag" VALUES
  (uuid_generate_v4(), 'Français - Lettres', true),
  (uuid_generate_v4(), 'Mathématiques', true),
  (uuid_generate_v4(), 'Histoire', true),
  (uuid_generate_v4(), 'Géographie', true),
  (uuid_generate_v4(), 'Technologie', true),
  (uuid_generate_v4(), 'Ëducation civique', true),
  (uuid_generate_v4(), 'Sciences Physiques', true),
  (uuid_generate_v4(), 'Sport', true),
  (uuid_generate_v4(), 'Sciences de la Vie', true),
  (uuid_generate_v4(), 'Langues', true),
  (uuid_generate_v4(), 'Musique', true),
  (uuid_generate_v4(), 'Arts', true),
  (uuid_generate_v4(), 'Economie', true),
  (uuid_generate_v4(), 'Philosophie', true),
  (uuid_generate_v4(), 'Projets de recherche', true);
