FROM node:latest
RUN mkdir -p /usr/src/app/client
WORKDIR /usr/src/app/client
COPY client/package.json /usr/src/app/client
COPY client/yarn.lock /usr/src/app/client
RUN yarn
WORKDIR /usr/src/app
COPY package.json /usr/src/app
COPY yarn.lock /usr/src/app
RUN yarn
COPY . /usr/src/app
RUN yarn build
ENV NODE_ENV=production
ENV CELLULOID_LISTEN_PORT=8000
EXPOSE 8000
CMD [ "yarn", "start"]
