FROM node:latest
WORKDIR /usr/src/app
RUN mkdir -p packages/{commons,client,server}
COPY package.json ./
COPY packages/commons/package.json packages/commons/
COPY packages/server/package.json packages/server/
COPY packages/client/package.json packages/client/
COPY yarn.lock ./
RUN yarn
COPY . ./
ENV NODE_ENV=production
RUN yarn build
ENV CELLULOID_LISTEN_PORT=8000
EXPOSE 8000
CMD [ "yarn", "start"]
