packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^5.9.3
  react: ^19.2.0
  react-dom: ^19.2.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  zod: ^3.23.8
  better-auth: ^1.2.10
  "@t3-oss/env-core": ^0.12.0

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - canvas
  - core-js
  - esbuild
  - prisma
  - sharp
  - vue-demi
