packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^5.6.3
  zod: ^3.23.8
  better-auth: ^1.2.4
  "@t3-oss/env-core": ^0.12.0

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
