version: "3.8"
name: celluloid-test-stack

volumes:
  app_db_data:

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: celluloid

  celluloid:
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgres://postgres:root@localhost:5432/celluloid
      COOKIE_SECRET: changethistosecretcookie
      COOKIE_DOMAIN: 127.0.0.1
      COOKIE_SECURE: false
      STORAGE_URL: http://localhost:9000
      STORAGE_BUCKET: celluloid
      STORAGE_ACCESS_KEY: root
      STORAGE_SECRET_KEY: StrongPass2022
    # image: celluloid-full:latest
    build:
      context: .
      dockerfile: ./Dockerfile.full
