version: "3.8"
name: celluloid-stack

volumes:
  database:
  storage:

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: celluloid

  celluloid-web:
    image: celluloid-web:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   target: web
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgres://postgres:root@localhost:5432/celluloid
      AUTH_SECRET: changethistosecretcookie
      STORAGE_URL: http://localhost:9000
      STORAGE_BUCKET: celluloid
      STORAGE_ACCESS_KEY: root
      STORAGE_SECRET_KEY: StrongPass2022

  celluloid-worker:
    image: celluloid-worker:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   target: worker
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgres://postgres:root@localhost:5432/celluloid
      STORAGE_URL: http://localhost:9000
      STORAGE_BUCKET: celluloid
      STORAGE_ACCESS_KEY: root
      STORAGE_SECRET_KEY: StrongPass2022


  minio:
    image: minio/minio
    volumes:
      - storage:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: StrongPass2022
    command: server /data
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
