const ActionType = {
  OPEN_LOGIN: 'OPEN_LOGIN',
  SUCCEED_LOGIN: 'SUCCEED_LOGIN',
  FAIL_LOGIN: 'FAIL_LOGIN',

  OPEN_SIGNUP: 'OPEN_SIGNUP',
  FAIL_SIGNUP: 'FAIL_SIGNUP',
  OPEN_CONFIRM_SIGNUP: 'OPEN_CONFIRM_SIGNUP',
  FAIL_CONFIRM_SIGNUP: 'FAIL_CONFIRM_SIGNUP',
  SUCCEED_SIGNUP: 'SUCCEED_SIGNUP',

  OPEN_RESET_PASSWORD: 'OPEN_RESET_PASSWORD',
  FAIL_RESET_PASSWORD: 'FAIL_RESET_PASSWORD',
  OPEN_CONFIRM_RESET_PASSWORD: 'OPEN_CONFIRM_RESET_PASSWORD',
  FAIL_CONFIRM_RESET_PASSWORD: 'FAIL_CONFIRM_RESET_PASSWORD',
  SUCCEED_RESET_PASSWORD: 'SUCCEED_RESET_PASSWORD',

  CLOSE_SIGNIN: 'CLOSE_SIGNIN',
  TRIGGER_SIGNIN_LOADING: 'TRIGGER_SIGNIN_LOADING',

  FAIL_CURRENT_USER: 'FAILED_CURRENT_USER',
  SUCCEED_CURRENT_USER: 'SUCCESS_CURRENT_USER',

  FAIL_LOGOUT: 'FAIL_LOGOUT'
};

export default ActionType;