/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * @celluloid/server
 * Celluloid backend
 * OpenAPI spec version: 2.0.0
 */
import type { Extra } from "./extra";

export interface ProjectResult {
  tags: string[];
  id: string;
  videoId: string;
  userId: string;
  title: string;
  description: string;
  host: string;
  assignments: string[];
  publishedAt: string;
  objective: string;
  levelStart: number;
  levelEnd: number;
  public: boolean;
  collaborative: boolean;
  shared: boolean;
  shareName: string;
  shareExpiresAt: string;
  sharePassword: string;
  extra: Extra;
}
