/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * @celluloid/server
 * Celluloid backend
 * OpenAPI spec version: 2.0.0
 */
import type { TagData } from "./tagData";

export interface ProjectCreateData {
  videoId: string;
  title: string;
  host: string;
  description?: string;
  objective: string;
  assignments: string[];
  tags: TagData[];
  levelStart: number;
  levelEnd: number;
  public: boolean;
  collaborative: boolean;
}
