/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * @celluloid/server
 * Celluloid backend
 * OpenAPI spec version: 2.0.0
 */
import type { UserRole } from "./userRole";

export interface UserRecord {
  id: string;
  username: string;
  role: UserRole;
  email?: string;
}
