/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * @celluloid/server
 * Celluloid backend
 * OpenAPI spec version: 2.0.0
 */

export type UserRole = typeof UserRole[keyof typeof UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  Admin: "Admin",
  Teacher: "Teacher",
  Student: "Student",
} as const;
