/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */

export interface AnalysisRequest {
  /** Project identifier */
  project_id: string;
  /** URL or path to video file */
  video_url: string;
  /**
   * Similarity threshold for object tracking
   * @minimum 0
   * @maximum 1
   */
  similarity_threshold?: number;
  /** Callback URL for job completion notifications */
  callback_url?: string | null;
}
