/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */
import type { DetectionStatisticsModelClassCounts } from "./detectionStatisticsModelClassCounts";

export interface DetectionStatisticsModel {
  total_detections?: number | null;
  person_detections?: number | null;
  person_with_face?: number | null;
  person_without_face?: number | null;
  other_detections?: number | null;
  class_counts?: DetectionStatisticsModelClassCounts;
}
