/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */
import type { DetectionFrameModel } from "./detectionFrameModel";
import type { ResultsMetadataModel } from "./resultsMetadataModel";

export interface DetectionResultsModel {
  version: string;
  metadata: ResultsMetadataModel;
  frames: DetectionFrameModel[];
}
