/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */
import type { DetectionObjectModel } from "./detectionObjectModel";

export interface DetectionFrameModel {
  frame_idx: number;
  timestamp: number;
  objects: DetectionObjectModel[];
}
