/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */
import type { BoundingBoxModel } from "./boundingBoxModel";

export interface DetectionObjectModel {
  id: string;
  class_name: string;
  confidence: number;
  bbox: BoundingBoxModel;
  thumbnail: string;
}
