/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */

export interface HealthResponse {
  status: string;
  timestamp: string;
  queue_size: number;
  processing_jobs: number;
  current_job: string | null;
}
