/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */

export * from "./analysisRequest";
export * from "./analysisResponse";
export * from "./boundingBoxModel";
export * from "./detectionFrameModel";
export * from "./detectionObjectModel";
export * from "./detectionResultsModel";
export * from "./detectionStatisticsModel";
export * from "./detectionStatisticsModelClassCounts";
export * from "./healthResponse";
export * from "./hTTPValidationError";
export * from "./jobCompletedWebhook";
export * from "./jobStatusResponse";
export * from "./jobStatusResponseMetadata";
export * from "./modelMetadataModel";
export * from "./processingMetadataModel";
export * from "./resultsMetadataModel";
export * from "./spriteMetadataModel";
export * from "./validationError";
export * from "./videoMetadataModel";
