/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */
import type { JobStatusResponseMetadata } from "./jobStatusResponseMetadata";

export interface JobStatusResponse {
  job_id: string;
  project_id: string;
  video_url: string;
  similarity_threshold: number;
  status: string;
  progress: number;
  queue_position: number | null;
  estimated_wait_time: string | null;
  start_time: string | null;
  end_time: string | null;
  result_path: string | null;
  metadata: JobStatusResponseMetadata;
  error_message: string | null;
}
