/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */
import type { DetectionStatisticsModel } from "./detectionStatisticsModel";

export interface ProcessingMetadataModel {
  start_time?: string | null;
  end_time?: string | null;
  duration_seconds?: number | null;
  frames_processed?: number | null;
  frames_with_detections?: number | null;
  processing_speed?: number | null;
  detection_statistics?: DetectionStatisticsModel | null;
}
