/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */
import type { ModelMetadataModel } from "./modelMetadataModel";
import type { ProcessingMetadataModel } from "./processingMetadataModel";
import type { SpriteMetadataModel } from "./spriteMetadataModel";
import type { VideoMetadataModel } from "./videoMetadataModel";

export interface ResultsMetadataModel {
  video: VideoMetadataModel;
  model: ModelMetadataModel;
  sprite: SpriteMetadataModel;
  processing: ProcessingMetadataModel;
}
