/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Celluloid Video Analysis API
 * OpenAPI spec version: 1.1.4
 */

export interface SpriteMetadataModel {
  path: string;
  thumbnail_size: number[];
}
